-- 코드를 작성해주세요
SELECT ED3.ID
FROM
(SELECT ED2.ID 
FROM ECOLI_DATA AS ED1 
JOIN ECOLI_DATA AS ED2
ON ED1.PARENT_ID IS NULL AND ED1.ID = ED2.PARENT_ID) AS ED22
JOIN ECOLI_DATA ED3
ON ED22.ID = ED3.PARENT_ID
ORDER BY ED3.ID

/*
ED1의 PARENT_ID 가 NULL인 ID와 ED2의 PARENT_ID가 같은 ID === 2세대 
2세대의 ID와 ED3의 PARENT_ID가 같은 ID === 3세대
*/