-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE , (SUM(SALES_AMOUNT)*PR.PRICE) AS SALES
FROM PRODUCT AS PR 
INNER JOIN
OFFLINE_SALE AS OS
ON PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY OS.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE

# 상품 코드 별 매출액 합계를 출력하는 SQL문 작성
# 매출액을 기준으로 "내림차순 (DESC)", 상품코드를 기준으로 오름차순