SELECT ID, IF(P.PER <=0.25,'CRITICAL',
              IF(P.PER <=0.5,'HIGH' ,
                IF(P.PER <=0.75,'MEDIUM','LOW'))) AS COLONY_NAME
FROM 
(SELECT ID, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) / COUNT(ID) OVER() AS PER
FROM ECOLI_DATA
ORDER BY PER) AS P
ORDER BY ID