-- 코드를 입력하세요
SELECT  MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
from MEMBER_PROFILE 
where SUBSTRING(date_of_birth,6,7)=03 and TLNO IS NOT NULL and gender='W'
order by MEMBER_ID;