-- 코드를 작성해주세요
SELECT YM.YEAR , (YM.MAX_SIZE-SIZE_OF_COLONY) AS YEAR_DEV, ED1.ID
    FROM ECOLI_DATA AS ED1
    JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)) AS YM
    ON YEAR(ED1.DIFFERENTIATION_DATE) = YM.YEAR
ORDER BY YM.YEAR,YEAR_DEV
