-- 코드를 작성해주세요
SELECT COUNT(FI.FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO AS FI JOIN 
(SELECT FISH_TYPE
FROM FISH_NAME_INFO AS FNI
WHERE FNI.FISH_NAME = 'BASS' OR FNI.FISH_NAME = 'SNAPPER') AS FT
ON FI.FISH_TYPE = FT.FISH_TYPE