-- 코드를 작성해주세요
SELECT FT.ID , FNI.FISH_NAME, FT.LENGTH
FROM 
(SELECT FI.ID, FI.FISH_TYPE, FI.LENGTH
FROM FISH_INFO FI
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_FISH
  ON FI.FISH_TYPE = MAX_FISH.FISH_TYPE
 AND FI.LENGTH = MAX_FISH.MAX_LENGTH) AS FT
 JOIN FISH_NAME_INFO AS FNI
 ON FT.FISH_TYPE = FNI.FISH_TYPE
 ORDER BY FT.ID
        
