-- 코드를 입력하세요
SELECT B.BOOK_ID,A.AUTHOR_NAME,date_format(B.PUBLISHED_DATE,'%Y-%m-%d')as PUBLISHED_DATE
from BOOK as B,AUTHOR as A
where B.AUTHOR_ID =A.AUTHOR_ID and B.CATEGORY='경제'
order by PUBLISHED_DATE