-- 코드를 입력하세요
SELECT BOOK_ID,AUTHOR_NAME,DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE
## 경제 카테고리에 속하는 도서들의 아이디 저자명 출판일을 출력
## 출판일을 기준으로 오름차순 정렬